### PR TITLE
New proposal AIP-16.md

### PR DESCRIPTION
**Pull request by ipmask12**
AERGO 10:1 merger with token swap from erc-20 to mainnet
(Total 500 million tokens to 50 million) 
1430 HOLD

### CODE REVIEW

**Comment by zjatan2** [comment]
good!!!!

**Comment by ipmask12** [comment]
We are gathering more opinions from Korean communities (Kakao, Telegram), etc. Additional updates are possible, and we plan to conduct an internal vote as well.

**Comment by ultrafellen** [comment]
We are discussing this proposal and will decide on a merge to master in the next few days.

**Review by ipmask12 — COMMENTED** [review]
Aside from voting, it seems like a good idea to pursue rebranding along with a 10:1 denomination

**Pull request merged**
